import numpy as np 
import matplotlib.pyplot as plt 
dataR10B = np.loadtxt("prelimdata/hvR10B.csv", delimiter=";", skiprows=1, unpack= True) 
dataR20A = np.loadtxt("prelimdata/hvR20A.csv", delimiter=";", skiprows=1, unpack= True) 

plt.axvline(x=825, linestyle='--', color='black', alpha=0.4)
plt.scatter(dataR10B[0], dataR10B[1])
plt.errorbar(dataR10B[0], dataR10B[1], yerr=np.sqrt(dataR10B[1]), fmt='o', capsize=4.0)
plt.fill_between(dataR10B[0][3:6], 443.5, 494.5,  color='red', hatch='//', alpha=0.4)
plt.xlabel(r'High Voltage / V')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/hvR10B.pdf')
plt.clf()
plt.axvline(x=875, linestyle='--', color='black', alpha=0.4)
plt.scatter(dataR20A[0], dataR20A[1])
plt.errorbar(dataR20A[0], dataR20A[1], yerr=np.sqrt(dataR20A[1]), fmt='o', capsize=4.0)
plt.fill_between(dataR20A[0][7:10], 737.3, 810,  color='red', hatch='//', alpha=0.4)
plt.xlabel(r'High Voltage / V')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/hvR20A.pdf')