import numpy as np 
import matplotlib.pyplot as plt 

data = np.loadtxt("prelimdata/threshR10.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=70, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][3:9], 0, 610,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshR10.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshR20.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=55, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][3:8], 0, 600,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshR20.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshR00.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=50, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][3:8], 0, 320,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshR00.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshR10_2.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=45, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][2:8], 0, 320,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshR10_2.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshR01.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=55, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][3:8], 0, 450,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshR01.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshR11.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=60, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][4:8], 0, 400,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshR11.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshL00.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=30, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][4:9], 0, 1400,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshL00.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshL10.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=35, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][4:10], 0, 2400,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshL10.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshL01.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=55, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][4:10], 0, 820,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshL01.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshL11.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=75, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][6:10], 0, 720,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshL11.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshL10_2.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=60, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][3:11], 0, 4500,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshL10_2.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshL20.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=50, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][3:9], 0, 490,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshL20.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshL21.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=50, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][2:5], 0, 480,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshL21.pdf')
plt.clf()

data = np.loadtxt("prelimdata/threshR21.csv", delimiter=";", skiprows=1, unpack= True)
plt.axvline(x=55, linestyle='--', color='black', alpha=0.4)
plt.scatter(data[0], data[1])
plt.errorbar(data[0], data[1], yerr=np.sqrt(data[1]), fmt='o', capsize=4.0)
plt.fill_between(data[0][2:6], 0, 500,  color='orange', hatch='//', alpha=0.4)
plt.xlabel(r'Threshold Voltage / mV')
plt.ylabel(r'Number of coincidences')
plt.tight_layout()
plt.grid(alpha=0.5)
plt.savefig('plots/threshR21.pdf')
plt.clf()